// <auto-generated />
using System;
using Cuuxi.SurePath.DAL.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cuuxi.SurePath.DAL.Migrations
{
    [DbContext(typeof(SurePathDbContext))]
    [Migration("20260513180000_AddCountries")]
    partial class AddCountries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("surepath")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cuuxi.SurePath.DAL.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Countries", "surepath");

                    b.HasData(
                        new { Code = "DK", Name = "Danmark", LanguageCode = "da" },
                        new { Code = "NO", Name = "Norge", LanguageCode = "no" },
                        new { Code = "SE", Name = "Sverige", LanguageCode = "sv" },
                        new { Code = "DE", Name = "Tyskland", LanguageCode = "de" });
                });

            modelBuilder.Entity("Cuuxi.SurePath.DAL.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", "surepath");
                });
#pragma warning restore 612, 618
        }
    }
}
